export default {
	GET_ALL_CATEGORIES_TYPE: 'getAllCategories',
	ADD_CATEGORY_TYPE: 'addProductCategory',
	DELETE_CATEGORY_TYPE: 'deleteProductCategory',
	UPDATE_CATEGORY_TYPE: 'updateProductCategory',
	GET_ALL_USER_ROLES_TYPE: 'allUserRoles',
	ADD_USER_ROLE_TYPE: 'addUserRole',
	DELETE_USER_ROLE_TYPE: 'deleteUserRole',
	GET_ALL_USER_STATUSES_TYPE: 'allUserStatuses',
	ADD_USER_STATUS_TYPE: 'addUserStatus',
	DELETE_USER_STATUS_TYPE: 'deleteUserStatus',
	GET_ALL_FILE_FOLDERS_TYPE: 'allFileFolders',
	ADD_FILE_FOLDER_TYPE: 'addFileFolder',
	DELETE_FILE_FOLDER_TYPE: 'deleteFileFolder',
	AUTH_LOGIN_TYPE: 'authLoginType',
	GET_ALL_ADMIN_MENUS_TYPE: 'allAdminMenus',
};
