export default {
	GET_ALL_CATEGORIES_API_PATH: 'categories/getAllCategories',
	ADD_CATEGORY_API_PATH: 'categories/addProductCategory',
	DELETE_CATEGORY_API_PATH: 'categories/deleteProductCategory',
	UPDATE_CATEGORY_API_PATH: 'categories/updateProductCategory',
	GET_ALL_USER_ROLES_API_PATH: 'userRoles/allUserRoles',
	ADD_USER_ROLE_API_PATH: 'userRoles/addUserRole',
	DELETE_USER_ROLE_API_PATH: 'userRoles/deleteUserRole',
	GET_ALL_USER_STATUSES_API_PATH: 'userStatuses/allUserStatuses',
	ADD_USER_STATUS_API_PATH: 'userStatuses/addUserStatus',
	DELETE_USER_STATUS_API_PATH: 'userStatuses/deleteUserStatus',
	GET_ALL_FILE_FOLDERS_API_PATH: 'fileFolders/allFileFolders',
	ADD_FILE_FOLDER_API_PATH: 'fileFolders/addFileFolder',
	DELETE_FILE_FOLDER_API_PATH: 'fileFolders/deleteFileFolder',
	AUTH_LOGIN_API_PATH: 'auth/login',
	GET_ALL_ADMIN_MENUS_API_PATH: 'adminMenu/allAdminMenus',
};
