export default {
	WELCOME: 'Welcome,',
	SIGN_IN_SUBTITLE: 'Sign In to continue',
	REGISTER: 'Register',
	HOME_TITLE: 'Video categories',
	VIDEOS_LIST_TITLE: 'Videos',
	SETTINGS_TITLE: 'Settings',
	VIDEO_TITLE: 'Video',
	LOADING: 'Loading...',
	PASSWORD_PLACEHOLDER: 'Password',
	FIRST_NAME_PLACEHOLDER: 'First name',
	LAST_NAME_PLACEHOLDER: 'Last name',
	EMAIL_PLACEHOLDER: 'Email',
	MOBILE_PLACEHOLDER: 'Mobile number',
	FORGOTTEN_PASSWORD: 'Forgot Password',
	FORGOT_PASSWORD: 'Forgot Password?',
	DONT_HAVE_ACCOUNT: 'Dont have an account? ',
	SIGNUP_PLACEHOLDER: 'Sign Up',
	ALREADY_HAVE_ACCOUNT: 'Already have an account? ',
	LOGIN_PLACEHOLDER: 'Login',
	PROFILE_TITLE: 'My profile',
	COMMENTS_TITLE: 'Comments',
	REPLIES_TITLE: 'Replies',
};
